=== msmunoz2/sandbox/Catalog-Desktop.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT library-catalog-entry (title,creator,media,location*,publication,description)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT media (media-type+)>
<!ELEMENT media-type (#PCDATA)>
<!ELEMENT location (physical-location*,reference-number)
<!ELEMENT physical-location (#PCDATA)>
<!ELEMENT reference-number (#PCDATA)>
<!ELEMENT publication (publication-date,publisher)>
<!ELEMENT publication-date (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== msmunoz2/sandbox/library-catalog-entry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog.css"?>
<!DOCTYPE library-catalog-entry.xml SYSTEM "Catalog-Desktop.dtd">

<library-catalog-entry>
<title> Born a Crime: Stories from a South African Childhood </title>
<creator> Trevor Noah </creator>
<media>
<media-type> Book </media-type>
</media>
<location>
<physical-location> D. H. Hill Jr. Library <physical-location>
<reference-number> PN2287.N557 A3 2016 </reference-number>
</location>
<publication>
<publication-date> 2016 </publication-date>
<publisher> New York: Spiegel & Grau </publisher>
</publication>
<description> Noah's path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth. Born to a white Swiss father and a black Xhosa mother, at the time such a union was punishable by five years in prison. As he struggles to find himself in a world where he was never supposed to exist, his mother is determined to save her son from the cycle of poverty, violence, and abuse that would ultimately threaten her own life. With an incisive wit and unflinching honesty, Noah weaves together a moving yet funny portrait of a boy making his way through a damaged world in a dangerous time. </description>
</library-catalog-entry>
